### ISSUE TITLE
Task creation - Error message: "UnboundLocalError: local variable 'isInputInteger' referenced before assignment"

### ISSUE THREAD

**Issue by mschmidtkorth** [mschmidtkorth/alfred-clickup-msk#20]
**Describe the bug**
Error message `UnboundLocalError: local variable 'isInputInteger' referenced before assignment` when trying to create a task via `cu` - see [here](https://clickup.canny.io/integrations/p/alfred-integration) for details (Andrew Ousley)

**To Reproduce**
-
**Expected behavior**
No error message shown; task should be creatable

**Alfred version**
Your version of Alfred, e.g. 4.0.8

**Debug log**
`[13:41:21.476] Logging Started...
[13:41:26.062] ClickUp[Script Filter] Queuing argument ''
[13:41:26.273] ClickUp[Script Filter] Script with argv '' finished
[13:41:26.276] ERROR: ClickUp[Script Filter] Code 1: .
13:41:26 workflow.py:2061 DEBUG    ---------- ClickUp (1.1.0) ----------
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:2343 DEBUG    update check not due
13:41:26 main.py:597 DEBUG    [ main() ] - 
13:41:26 main.py:220 DEBUG    [ firstRun() ]
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:2225 DEBUG    last run version: 1.1.0
13:41:26 workflow.py:2225 DEBUG    last run version: 1.1.0
13:41:26 main.py:235 DEBUG    [ checkConfig() ]
13:41:26 workflow.py:2461 DEBUG    got password : com.msk.clickup2.0:clickUpAPI
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 main.py:361 DEBUG    [ getNameFromInput() ] 
13:41:26 main.py:364 DEBUG    inputName: 
13:41:26 main.py:376 DEBUG    [ getContentFromInput() ] 
13:41:26 main.py:382 DEBUG    inputContent: 
13:41:26 main.py:394 DEBUG    [ getTagsFromInput() ] 
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 main.py:408 DEBUG    inputTags: []
13:41:26 main.py:435 DEBUG    [ getDueFromInput() ] 
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:26 workflow.py:2080 ERROR    local variable 'isInputInteger' referenced before assignment
Traceback (most recent call last):
File "/Users/andrewousley1/Dropbox (Unison Media)/z - MISC/Alfred.alfredpreferences/workflows/user.workflow.5B639CF7-5FBD-490E-907B-971E22BCABA3/workflow/workflow.py", line 2073, in run
func(self)
File "main.py", line 717, in main
inputDue = getDueFromInput(query)
File "main.py", line 515, in getDueFromInput
elif isInputInteger:
UnboundLocalError: local variable 'isInputInteger' referenced before assignment
13:41:26 workflow.py:2103 DEBUG    ---------- finished in 0.038s ----------
[13:41:26.280] ClickUp[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'ClickUp'</title><subtitle>local variable 'isInputInteger' referenced before assignment</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[13:41:28.987] ClickUp[Script Filter] Queuing argument 'd'
[13:41:29.191] ClickUp[Script Filter] Script with argv 'd' finished
[13:41:29.201] ERROR: ClickUp[Script Filter] Code 1: .
13:41:29 workflow.py:2061 DEBUG    ---------- ClickUp (1.1.0) ----------
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:2343 DEBUG    update check not due
13:41:29 main.py:597 DEBUG    [ main() ] - d
13:41:29 main.py:220 DEBUG    [ firstRun() ]
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:2225 DEBUG    last run version: 1.1.0
13:41:29 workflow.py:2225 DEBUG    last run version: 1.1.0
13:41:29 main.py:235 DEBUG    [ checkConfig() ]
13:41:29 workflow.py:2461 DEBUG    got password : com.msk.clickup2.0:clickUpAPI
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 main.py:361 DEBUG    [ getNameFromInput() ] 
13:41:29 main.py:364 DEBUG    inputName: d
13:41:29 main.py:376 DEBUG    [ getContentFromInput() ] 
13:41:29 main.py:382 DEBUG    inputContent: 
13:41:29 main.py:394 DEBUG    [ getTagsFromInput() ] 
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 main.py:408 DEBUG    inputTags: []
13:41:29 main.py:435 DEBUG    [ getDueFromInput() ] 
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:1468 DEBUG    reading settings from /Users/andrewousley1/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
13:41:29 workflow.py:2080 ERROR    local variable 'isInputInteger' referenced before assignment
Traceback (most recent call last):
File "/Users/andrewousley1/Dropbox (Unison Media)/z - MISC/Alfred.alfredpreferences/workflows/user.workflow.5B639CF7-5FBD-490E-907B-971E22BCABA3/workflow/workflow.py", line 2073, in run
func(self)
File "main.py", line 717, in main
inputDue = getDueFromInput(query)
File "main.py", line 515, in getDueFromInput
elif isInputInteger:
UnboundLocalError: local variable 'isInputInteger' referenced before assignment
13:41:29 workflow.py:2103 DEBUG    ---------- finished in 0.041s ----------
[13:41:29.205] ClickUp[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'ClickUp'</title><subtitle>local variable 'isInputInteger' referenced before assignment</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>`

**Screenshots**

> after I input and validate all settings, I get an error message below
![image](https://user-images.githubusercontent.com/45070265/103581033-81f42e80-4edb-11eb-81ea-d5eeb1a9a0e7.png)

**Additional context**
-

**Comment by mschmidtkorth** [comment]
I've fixed the issue - to be tested. I'm going to publish this as an official release once confirmed.

Please rename the file from "ClickUp-1.1.1.alfredworkflow.zip" to "ClickUp-1.1.1.alfredworkflow" and open it to install.

[ClickUp-1.1.1.alfredworkflow.zip](https://github.com/mschmidtkorth/alfred-clickup-msk/files/5766868/ClickUp-1.1.1.alfredworkflow.zip)
